Отрисуй меня полностью (часть 1)
htmlacademy-javascript/907585-keksobooking-23 pull request #5
Opened 2021-06-20 11:31 UTC by EMedved-bit

2021-06-22 11:08 UTC, klymenko-oleksandr requested changes
Хорошая работа, пару моментов для доработки оставил

2021-06-22 11:08 UTC, klymenko-oleksandr commented on js/adverts.js
> +function addValue (element, value, isAdd = true) {
1. Подскажи для чего 3й параметр у функции?
2. Название функции не совсем отвечает тому что она делает(она ведь может еще и удалять элемент)

2021-06-22 11:08 UTC, klymenko-oleksandr commented on js/adverts.js
> +  advertElement.querySelector('.popup__avatar').src = advert.author.avatar;
Вижу что не для всех параметров предусмотрено отсутствие данных -- я наткнулся на 10го юзера для аватарки, а такой картинки нет => получил ломанную картинку

2021-06-22 18:12 UTC, EMedved-bit commented on js/adverts.js
> +function addValue (element, value, isAdd = true) {
Это дополнительное условие для тех случаев, где проверки на наличие value недостаточно. Там где в качестве value передается собранная строка - value плюс какой-то текст.

2021-06-22 18:21 UTC, EMedved-bit commented on js/adverts.js
> +  advertElement.querySelector('.popup__avatar').src = advert.author.avatar;
Я сделала проверку, а в шаблоне поменяла картинку на дефолтную. Мне кажется, странно полностью убирать блок с аватаркой.

2021-06-23 08:10 UTC, klymenko-oleksandr approved these changes
Супер, молодец

2021-06-23 08:12 UTC, merged